export const actionTypes = {
  SET_STATES: "SET_STATES",

  SELECT_STATE: "SELECT_STATE",
  SET_DISTRICTS: "SET_DISTRICTS",

  SELECT_DISTRICT: "SELECT_DISTRICT",
  
  TOGGLE_LANDING_DRAWER: "TOGGLE_LANDING_DRAWER",
};

